### ISSUE TITLE
OS error 2 with existing wine prefix and game installation

### ISSUE THREAD

**Issue by FichteFoll** [an-anime-team/an-anime-game-launcher-gtk#2]
The default configuration works (removing the config file to restore defaults), but as soon as I try to use my **already existing** wine prefix at `~/games/genshin-impact` together with the installed game I get greeted with an error message without a lot of details. 

The following changes to my config file are enough to trigger the issue:

```diff
--- /home/fichte/.local/share/anime-game-launcher/config.json	Fri Aug 26 22:20:00 2022
+++ /home/fichte/.local/share/anime-game-launcher/config.json	Fri Aug 26 22:20:09 2022
@@ -9,12 +9,12 @@
     "edition": "Global"
   },
   "game": {
-    "path": "/home/fichte/.local/share/anime-game-launcher/game/drive_c/Program Files/Genshin Impact",
+    "path": "/home/fichte/games/genshin-impact/drive_c/Program Files/Genshin Impact",
     "voices": [
       "en-us"
     ],
     "wine": {
-      "prefix": "/home/fichte/.local/share/anime-game-launcher/game",
+      "prefix": "/home/fichte/games/genshin-impact",
       "builds": "/home/fichte/.local/share/anime-game-launcher/runners",
       "selected": null,
       "sync": "FSync",
```

When I don't have a wine runner selected in the config (`null`), I can reach the stage where I download wine, but trying to open the preferences yields "Failed to update preferences" and the error message after pressing on the dialog is the standard "No such file or directory (os error 2)".  Nothing on stdout.

When I add a wine prefix from to the config file, I am immediately greeted with "Failed to get initial launcher state" and the same error message.

**Comment by FichteFoll** [comment]
Removing the game path opens the "Download" button for downloading the game. Removing the wine prefix offers me to create the prefix.

Since I didn't want to re-download the entire game, I created a new prefix, but unfortunately that turned out to not help at all as the application is now stuck in "Loading data" and
```
thread '<unnamed>' panicked at 'main context already acquired by another thread: BoolError { message: "Failed to acquire ownership of main context, already acquired by another thread", filename: "/home/observer/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.15.12/src/main_context.rs", function: "glib::main_context", line: 172 }', /home/observer/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.15.12/src/main_context_channel.rs:543:18
```

**Comment by krypt0nn** [comment]
Should suddenly become fixed, so closed

**Comment by FichteFoll** [comment]
Still reproduces with 1.0.4. Is this only on `master`?

**Comment by krypt0nn** [comment]
I thought I fixed it in earlier versions. Re-open this issue then xd

**Comment by GeoffreyCoulaud** [comment]
This is still an issue, I've only changed the game directory and the OS error 2 message is still happening.  
I'm using the flatpak, and I've given permanent access to the game directory via Flatseal btw.

**Comment by TeamBattino** [comment]
the fix is to change the in the install folder and then delete the folder the game would be installed into so the launcher can make a new one by itself..

**Comment by FichteFoll** [comment]
But the entire idea of this is to re-use an already existing installation of the game.
